baseURL = "https://apmyp.pro/"
languageCode = "ru-ru"
title = "Апмип.про"
theme = "default"

[taxonomies]
	category	= "categories"

[params]
	description = "Артур Борденюк ведет блог о разработке, продуктоводстве, опенсорсе, проектном управлении и философии, новый пост каждую неделю"
	keywords = "блог о разработке, проектное управление, философия, управление рисками, опенсорс, opensource"
	Tagline = "Arthur Bordenyuk makes you be aware of mindfulness"
	author = "Arthur Bordenyuk"
	og_image = "og_image.png"
  twitter_og_image = "twitter_og_image.png"
	twitter = "@apmyp0"

[params.podcast]
  title = "Подкаст Apmyp"
  description = "Подкаст о разработке, продуктоводстве и жизни"
  author = "Arthur Bordenyuk"
  email = "podcast@apmyp.pro"
  image = "https://r2-url/podcast-cover.jpg"
  language = "ru-RU"
  explicit = false
  categories = ["Technology", "Business"]
  keywords = "разработка, менеджмент, подкаст"

[params.remark42]
  host = "https://comments.apmyp.pro"
  site_id = "apmyp.pro"

[markup]
  [markup.goldmark.renderer]
    unsafe= true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "xcode"
    tabWidth = 4

[outputFormats.podcast]
  mediaType = "application/rss+xml"
  baseName = "podcast"
  isPlainText = false

[outputs]
  home = ["HTML", "RSS", "podcast"]
