baseURL = "https://apmyp.pro/"
languageCode = "ru-ru"
title = "Апмип.про"
theme = "default"

[taxonomies]
	category	= "categories"

[params]
	description = "Артур Борденюк ведет блог о разработке, продуктоводстве, опенсорсе, проектном управлении и философии, новый пост каждую неделю"
	keywords = "блог о разработке, проектное управление, философия, управление рисками, опенсорс, opensource"
	Tagline = "Arthur Bordenyuk makes you be aware of mindfulness"
	author = "Arthur Bordenyuk"
	og_image = "og_image.png"
	twitter = "@apmyp0"
